# Generated by Django 4.1.4 on 2022-12-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('susers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('detail_address', models.TextField()),
                ('phone', models.TextField()),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='susers.susers')),
            ],
            options={
                'db_table': 'shop_deliveries',
            },
        ),
    ]
