FROM mysql:5.7
# COPY conf.d/my.cnf etc/mysql/my.cnf

# ENTRYPOINT grant all privileges on *.* to 'root'@'%' identified by 'root';
# RUN grant all privileges on *.* to 'root'@'%' identified by 'root';