# Generated by Django 4.1.4 on 2022-12-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theater', '0001_initial'),
        ('musers', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater_tickets',
            fields=[
                ('teaher_tickets_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('movie_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musers.musers')),
                ('showtimes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.showtimes')),
                ('theaters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theaters')),
            ],
            options={
                'db_table': 'movies_theater_tickets',
            },
        ),
    ]
