-- insert into users(user_id, user_email, password, user_name, phone, birth,
--   address, job, user_interests)
-- values ('1','crmk@test.com', '1', '홍길동', '010-4575-2631', '1993-5-24', '대구', '사업가', '영화');
--
-- insert into users(user_id, user_email, password, user_name, phone, birth,
--   address, job, user_interests)
-- values ('2','kdmv@test.com', '1', '신진준', '010-8298-2839', '1998-4-6', '경기', '개발자', '영화');
--
-- insert into articles(art_seq, title, content, created_at, updated_at)
-- values ('1','졸림', '조올리임', '집', '11');
--
-- insert into articles(art_seq, title, content, created_at, updated_at)
-- values ('2','고시원살이', '내방개추움', '홈', '22');
--
-- insert into users(user_id, user_email, password, user_name, phone, birth, address, job, user_interests)
-- values (UNHEX(REPLACE(UUID(),'-','')),'hong@test.com', '1', '홍길동', '010-1234-5678', '2000-01-01', '서울시 강남구', '개발자', '영화');
--
-- insert into users(user_id, user_email, password, user_name, phone, birth, address, job, user_interests)
-- values ('2','kdmv@test.com', '1', '신진준', '010-8298-2839', '1998-4-6', '경기', '개발자', '영화');
--
-- insert into articles(title, content)
-- values ('number1', 'test1');
--
-- insert into articles(title, content)
-- values ('number2', 'test2');
--
-- select * from users;
--
-- select * from articles;