# Generated by Django 4.1.4 on 2022-12-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('busers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('views_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('blog_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busers.busers')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
            options={
                'db_table': 'blog_views',
            },
        ),
    ]
