# Generated by Django 4.1.4 on 2022-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movies_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('director', models.TextField()),
                ('description', models.TextField()),
                ('poster_url', models.TextField()),
                ('running_time', models.TextField()),
                ('age_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'movies_movie',
            },
        ),
    ]
